### ISSUE TITLE
Can we stop requiring release archives to be uploaded as part of publishing the release

### ISSUE THREAD

**Issue by lalten** [bazel-contrib/publish-to-bcr#140]
BCR likes source archives to be uploaded as release artifact rather than relying on the automatic source artifact for commits and tags which is known to not have a guaranteed hash.
Currently if users configure publish-to-bcr to point at a release artifact in the source.template.json, the app will fail with the message `ensure that the release archive is uploaded as part of publishing the release rather than uploaded afterward.`.

GitHub supports a workflow where it automatically tags the repo with the a tag chosen in the release "editor". I like that approach because it saves me some brain power trying to do the tagging exactly right using git. The drawback is that I can't use GitHub Actions to publish the release on tag creation like suggested in the https://github.com/bazel-contrib/rules-template/blob/main/.github/workflows/release.yml

I don't know if it really makes sense that the app stops on the mentioned error. The BCR PR could be made anyways. It will fail if CI runs on it -- but only until the author has manually attached the release artifact to the release.

Another idea to work around this issue would be to have the bot download the automatic source archive and re-upload it as the attached release archive.

Curious about people's opinions here.

**Comment by kormide** [comment]
I think it makes sense that not being able to download the release archive shouldn't cause a hard failure. The release archive needs to be present to calculate the correct integrity value, but the PR could always be manually amended after it's up.

I'll think about this some more and let it stew.

**Comment by kormide** [comment]
Actually, I don't think this will be possible. The MODULE.bazel file in the release archive is the source of truth for the module name which forms the path in the BCR repo, and the module file itself that appears in the BCR entry. It's not required that a module published to the BCR comes from a source archive that even has a MODULE.bazel file. This was the case for at least some rulesets were made available via bzlmod before supporting being built with bzlmod themselves.

**Comment by kormide** [comment]
There is some leniency for release archives that are uploaded shortly after the release is created. The download happens with retries and exponential backoff. I could increase the number of retries if that would be helpful.

**Comment by lalten** [comment]
Haha or maybe it did something? The bot did put up https://github.com/bazelbuild/bazel-central-registry/pull/1436 and apparently failed to interpolate some vars in the process.

**Comment by ouillie** [comment]
I just ran into this same problem. My release-publishing workflow took only [30 seconds](https://github.com/vimana-cloud/rules_wasm/actions/runs/11221375970) to run, but it was not finished in time for the app to find it, and it reported a 404 (but clicking the link in the email just after I received it worked fine).

Right now the app uses [Axios' default exponential backoff](https://github.com/bazel-contrib/publish-to-bcr/blob/db12297431c3fdc71afae0e8c749dda944c3d451/src/domain/release-archive.ts#L130) which tries once, then waits somewhere between [100 - 120ms](https://github.com/softonic/axios-retry/blob/756dd7bbf1d0106f64903ca8563de27747c5efa0/src/index.ts#L170) before the first retry, then 200 - 240ms before the second, and 400 - 480ms before the third. So, the maximum time a release-publishing workflow can take is 700ms after the app kicks off in order to get picked up reliably (assuming the lower end of the delay ranges). There's probably some extra time while the app is getting started, but this still seems too low for effective exponential backoff.

Why don't we increase the `delayFactor`? Right now it uses the default 100ms. If we make it 10 seconds, then release-publishing workflows will have at least 70 seconds to run, but the app will still report fetch errors within ~84 seconds.

**Comment by kormide** [comment]
> I just ran into this same problem. My release-publishing workflow took only [30 seconds](https://github.com/vimana-cloud/rules_wasm/actions/runs/11221375970) to run, but it was not finished in time for the app to find it, and it reported a 404 (but clicking the link in the email just after I received it worked fine).
> 
> Right now the app uses [Axios' default exponential backoff](https://github.com/bazel-contrib/publish-to-bcr/blob/db12297431c3fdc71afae0e8c749dda944c3d451/src/domain/release-archive.ts#L130) which tries once, then waits somewhere between [100 - 120ms](https://github.com/softonic/axios-retry/blob/756dd7bbf1d0106f64903ca8563de27747c5efa0/src/index.ts#L170) before the first retry, then 200 - 240ms before the second, and 400 - 480ms before the third. So, the maximum time a release-publishing workflow can take is 700ms after the app kicks off in order to get picked up reliably (assuming the lower end of the delay ranges). There's probably some extra time while the app is getting started, but this still seems too low for effective exponential backoff.
> 
> Why don't we increase the `delayFactor`? Right now it uses the default 100ms. If we make it 10 seconds, then release-publishing workflows will have at least 70 seconds to run, but the app will still report fetch errors within ~84 seconds.

Thanks for investigating the timing. I'll increase the delayFactor.

**Comment by ouillie** [comment]
I've already submitted https://github.com/bazel-contrib/publish-to-bcr/pull/170 for review.

**Comment by kormide** [comment]
> I've already submitted #170 for review.

Oh I missed that. I'll take a look :eyes:

**Comment by ouillie** [comment]
Hm, I just got another email like this:

```
Failed to download release archive from https://github.com/vimana-cloud/rules_wasm/releases/download/v1.0.13/rules_wasm-v1.0.13.tar.gz. Received status 404

**Comment by ouillie** [comment]
Ah, I suppose I did fail to solve the problem. Looks like `axios-retry` considers 404 to be ["unsafe"](https://github.com/softonic/axios-retry/blob/756dd7bbf1d0106f64903ca8563de27747c5efa0/spec/index.spec.ts#L999). Looks like we have to override [`retryCondition`](https://github.com/softonic/axios-retry/blob/756dd7bbf1d0106f64903ca8563de27747c5efa0/src/index.ts#L25) too.

**Comment by ouillie** [comment]
Just put up #172 for your consideration.

**Comment by kormide** [comment]
Looks like the release was successful https://github.com/bazelbuild/bazel-central-registry/pull/2969 :tada:

**Comment by ouillie** [comment]
Yes, thanks for the reviews!
