### ISSUE TITLE
`An unknown error occurred` for lalten/rules_appimage@v1.7.5

### ISSUE THREAD

**Issue by lalten** [bazel-contrib/publish-to-bcr#148]
Hi, I'm getting

> Failed to publish entry for [lalten/rules_appimage@v1.7.5](mailto:lalten/rules_appimage@v1.7.5) to the Bazel Central Registry.
> An unknown error occurred. Please report an issue here: https://github.com/bazel-contrib/publish-to-bcr/issues.

Any pointers what the issue is? It would be really helpful to include more details. If not the stack trace, at least the file and line that failed...

**Comment by kormide** [comment]
You need to accept new app permissions on Publish to BCR. I updated them a while ago and it should have notified you.

See https://bazelbuild.slack.com/archives/C014RARENH0/p1707187780032139.

**Comment by kormide** [comment]
In general I try to add friendly messages for common and detectable cases and they come up, but this one shouldn't be recurring.

**Comment by lalten** [comment]
Thanks for the super quuick response @kormide. I didn't get any notification about permissions :shrug: I went to https://github.com/settings/installations/ and there clicked on "configure" for the BCR app. Only then it showed me a box that the app is requesting updated permissions :shrug:
Also synced the BCR fork. Trying again, :crossed_fingers:

**Comment by kormide** [comment]
> Thanks for the super quuick response @kormide. I didn't get any notification about permissions 🤷 I went to https://github.com/settings/installations/ and there clicked on "configure" for the BCR app. Only then it showed me a box that the app is requesting updated permissions 🤷 Also synced the BCR fork. Trying again, 🤞

Weird. I figured it would have emailed everyone or at least tried to get your attention in GitHub :/
