### ISSUE TITLE
Publishing to BCR stopped working for protobuf

### ISSUE THREAD

**Issue by zhangskz** [bazel-contrib/publish-to-bcr#165]
The publish-to-bcr app seems to have stopped working for https://github.com/protocolbuffers/protobuf as of our recent v28.0-rc3 and v27.4 releases: https://github.com/protocolbuffers/protobuf/issues/17998

No commit or PR was made by the app to/from our bazel-central-registry fork. It doesn't look like there have been recent changes to protobuf's .bcr files or MODULE.bazel, nor publish-to-bcr itself.
This [PR](https://github.com/protocolbuffers/protobuf/pull/17934) was cherry-picked to both branches, but doesn't seem to be related. Creating [PR](https://github.com/bazelbuild/bazel-central-registry/pull/2757) manually to publish to BCR seems to have worked fine: 

I have double checked / fixed our app [configurations](https://screenshot.googleplex.com/3QnkLopBM7mLD9y) that access is granted to the ruleset repo and bazel-central-registry fork, but this was still broken for the latest v28.1 release

Are there logs somewhere to help understand what changed here?

**Comment by kormide** [comment]
It looks like for protobuf releases specifically the cloud function is running out of memory and crashes. I increased the limit and deployed to prod. Let's leave the ticket open until your next release to see if it works.

**Comment by zhangskz** [comment]
Thanks! Can confirm after our next release. Is there a trigger to run re-run publish-to-bcr manually when it fails? Are there logs somewhere we can access to investigate in the future?

Also, anything notable about protobuf releases s.t. we are hitting these OOM / crash but seems like not others?

**Comment by kormide** [comment]
> Thanks! Can confirm after our next release. Is there a trigger to run re-run publish-to-bcr manually when it fails? Are there logs somewhere we can access to investigate in the future?
> 
Unfortunately there isn't an easy way to retrigger as it runs on a release webhook event. You could manually delete and then re-publish the release. It's often easiest to just cut a new patch version. In the future I expect Publish to BCR will be offered as a GitHub Action, so you could have more control over re-runs, but likely not until next quarter.

You should receive an email notification on failure, but unfortunately the OOM case doesn't do this. I need to set up proper alerting so I can be a bit more proactive about failures like this, but haven't gotten around to it.

> Also, anything notable about protobuf releases s.t. we are hitting these OOM / crash but seems like not others?

I'll have to investigate this some more.

**Comment by zhangskz** [comment]
Confirming that this seems to have worked for our latest release: https://github.com/bazelbuild/bazel-central-registry/pull/2805#event-14314066738

**Comment by kormide** [comment]
Glad to hear it works! I landed [this](https://github.com/bazel-contrib/publish-to-bcr/commit/82a77ee06de268666bd10f996eb6140770be93db_) to see if it helps with the memory footprint. I'll close this issue for now but I'll keep an eye on the RAM metrics.
