### ISSUE TITLE
[Feature request] Support `.tar.xz` release archives

### ISSUE THREAD

**Issue by jmillikin** [bazel-contrib/publish-to-bcr#169]
I recently tried to use publish-to-bcr for one of my rulesets, but it failed to publish because the release archive was an unsupported format.

> Failed to publish entry for jmillikin/rules_bison@v0.3 to the Bazel Central Registry.
>
> Unsupported release archive format 3.tar.xz

Looking at [`src/domain/release-archive.ts`](https://github.com/bazel-contrib/publish-to-bcr/blob/db12297431c3fdc71afae0e8c749dda944c3d451/src/domain/release-archive.ts), it seems that only `.tar.gz` is currently supported.

Could that code be made more flexible? Bazel supports quite a number of file extensions for tarballs (see [`download_and_extract`](https://bazel.build/rules/lib/builtins/repository_ctx#download_and_extract) docs), including `.tar.bz2`, `.tar.xz`, and `.tar.zst`.

**Comment by kormide** [comment]
Looking at some candidate NPM packages, this one seems promising: https://github.com/SteveSanderson/xzwasm?tab=readme-ov-file#what-about-tarxz-files

**Comment by jmillikin** [comment]
Rough work-in-progress branch of decompressing `.tar.xz` archives using `liblzma` (via WebAssembly): https://github.com/bazel-contrib/publish-to-bcr/compare/main...jmillikin:upstream__publish-to-bcr:xz-artifacts?expand=1

Summary:
* Local branch of https://github.com/bazel-contrib/toolchains_llvm to support `wasm32-unknown-unknown` targets.
* Local branch of https://github.com/bazelbuild/bazel-central-registry/tree/main/modules/xz to add a `config.h` (+ other small patches)
* Wrote a thin wrapper around `@xz//:lzma` that exposes a Wasm-friendly API for decoding.
* Modified `release-archive.ts` so it'll decompress `.tar.xz` files before passing them into `tar.extract()`
* Checked in the compiled `xzdec.wasm` file because it's ~100 KB and the LLVM dependencies to build it are enormous.

What do the owners of this repository think of that branch? Should I try polishing it up to turn into a PR, or would you prefer a different approach?

---

I looked into the `xzwasm` package linked above, and it seems challenging from a maintenance standpoint:
* The most recent version was v0.1.2, published three years ago, with no commits since then.
* It's not using the standard `xz` library `liblzma`, but instead https://github.com/tukaani-project/xz-embedded which appears to be intended for use in the Linux kernel and says on its homepage "There are no release packages and no API/ABI stability guarantees".
* It's shipping the WebAssembly module as part of a 20 KB `xzwasm.min.js`, which makes it difficult to review.
* I couldn't find any way to limit the memory consumption of the decompressor, so it's potentially vulnerable to denial-of-service from malicious inputs.

There's a fork of that package at https://www.npmjs.com/package/xz-decompress with a slightly more active maintainer (v0.2.2 was published 4 months ago), but the other difficulties still apply.

**Comment by kormide** [comment]
Thanks for you work and investigation into this @jmillikin! I haven't used WebAssembly before. Just to confirm my understanding, you brought in Bazel just to get the necessary toolchains to generate the wasm binary? I would like to migrate this repo to use Bazel eventually, but I'm not quite there yet. I suppose we could just vendor the files you generated and leave the additional Bazel stuff in a separate branch in case we ever need to re-generate it?

**Comment by jmillikin** [comment]
I'd prefer to not have a separate branch for the build configuration, for technical and legal reasons. How about I put the Bazel configuration under `src/infrastructure/xzdec/`? Then if the overall build ever migrates to Bazel, the xzdec config can just be moved up to the top level.

**Comment by kormide** [comment]
> I'd prefer to not have a separate branch for the build configuration, for technical and legal reasons. How about I put all of the Bazel configuration into the main branch, but under `src/infrastructure/xzdec/`? Then if the overall build ever migrates to Bazel, the xzdec config can just be moved up to the top level.

That works. Let's move the bazel module under `src/domain/xzdec`, then use a [write_source_file](https://docs.aspect.build/rulesets/aspect_bazel_lib/docs/write_source_files/#write_source_file) target to write it to the source tree.

**Comment by kormide** [comment]
Thanks again for your contribution @jmillikin! Your work has been deployed to prod.
