### ISSUE TITLE
Publish failed due to "Could not find MODULE.bazel", not sure how to debug

### ISSUE THREAD

**Issue by jmillikin** [bazel-contrib/publish-to-bcr#176]
I just cut rules_m4 v0.2.4 (https://github.com/jmillikin/rules_m4/releases/tag/v0.2.4), but publish-to-bcr failed:

```
Failed to publish entry for jmillikin/rules_m4@v0.2.4 to the Bazel Central Registry.

Could not find MODULE.bazel in release archive at ./MODULE.bazel.
Is the strip prefix in source.template.json correct? (currently it's '')
```

The source archive does contain a `MODULE.bazel` file at the top level:
```
$ tar -tf rules_m4-v0.2.4.tar.xz | grep MODULE
MODULE.bazel
```

I suspect the underlying cause is somewhere in the recently-added `.tar.xz` support (is it not extracting properly?), but the error email contains no logs or information so it's difficult to debug.

**Comment by jmillikin** [comment]
Gentle ping @kormide -- do the logs show anything that might be related? I've not been able to figure out how to get this project to run locally for testing.

**Comment by kormide** [comment]
Sorry for the delay. I'll fork your repo and try to reproduce it in the dev environment I have set up.

**Comment by kormide** [comment]
How do you produce and upload the release archive?

**Comment by kormide** [comment]
I found the issue. We aren't waiting for the writable stream to close after decompressing. Fixing this revealed another bug. I'll get some fixes up soon.

**Comment by kormide** [comment]
After fixing the waiting issue, it seems that the extracted contents are not correct. For example, it's trying to parse the extracted MODULE.bazel file, but that file contains contents from your [m4_repository.bzl](https://github.com/jmillikin/rules_m4/blob/05b8762ea36896016fe0fb414c97c14d86a32639/m4/rules/m4_repository.bzl#L48) file.

**Comment by jmillikin** [comment]
I was able to reproduce the incorrect `MODULE.bazel` content, but I'm confused about why it's happening. The output stream is observing chunks of bytes being written in the wrong order -- I can `console.log` to verify the decompressed bytes are correct, but the stream is seeing chunk 2 being written with the contents of chunk 3.

Is it possible that Node's file streams require explicit synchronization to preserve order between calls? This doesn't make sense to me, but the following diff seems to fix the problem (the logged bytes and streamed bytes become the same).

```diff
diff --git a/src/infrastructure/xzdec/xzdec.ts b/src/infrastructure/xzdec/xzdec.ts
index 208d150..5fd9efc 100644
--- a/src/infrastructure/xzdec/xzdec.ts
+++ b/src/infrastructure/xzdec/xzdec.ts
@@ -126,7 +126,11 @@ export async function decompress(r: stream.Readable, w: stream.Writable) {
           }
           const outputLen = peekU32(mem, outputLenPtr);
           if (outputLen > 0) {
-            w.write(Buffer.from(mem.buffer, outputPtr, outputLen));
+            await (new Promise((resolve) => {
+                w.write(Buffer.from(mem.buffer, outputPtr, outputLen), () => {
+                    resolve(null);
+                });
+            }));
           }
         }
       }
```

**Comment by kormide** [comment]
The fixes have been deployed to prod.
