### ISSUE TITLE
A repository that publishes multiple modules to BCR

### ISSUE THREAD

**Issue by UebelAndre** [bazel-contrib/publish-to-bcr#177]
Hi, I am working on https://github.com/bazelbuild/rules_rust/issues/2882 for `rules_rust` where we're splitting out some 3rd party integrations into their own workspace but want to keep the code within the repo for ease of testing and integration. Is there a way to have `publish-to-bcr` publish more than one item to BCR for a release in a repository?

**Comment by UebelAndre** [comment]
Ah, I believe this is possible via `moduleRoots`
https://github.com/bazel-contrib/publish-to-bcr/blob/0b382f4d3d62100d43e121f62430ccc6d600f4dd/templates/README.md?plain=1#L103

**Comment by jsharpe** [comment]
`rules_python` does this for its gazelle plugin: https://github.com/bazelbuild/rules_python/tree/main/.bcr

**Comment by UebelAndre** [comment]
Closing now that I know it's possible. Thank you!
