### ISSUE TITLE
An unknown error occurred

### ISSUE THREAD

**Issue by keith** [bazel-contrib/publish-to-bcr#44]
I got this error pushing a new module to the BCR:

>Failed to publish entry for keith/rules_multirun@0.3.0 to the Bazel Central Registry.
>An unknown error occurred. Please report an issue here: https://github.com/bazel-contrib/publish-to-bcr/issues.

I imagine it could be because it was the first version and not an update. I'm not sure if I can view logs anywhere else to see details?

**Comment by kormide** [comment]
This was related to an incorrect strip_prefix in source.template.json. There should be a better user-facing error to indicate what the problem is.

**Comment by kormide** [comment]
> I also just saw an error like that
> 
> > Failed to publish entry for tweag/rules_nixpkgs@v0.10.0 to the Bazel Central Registry.
> 
> Is there any way to see what cause the problem?

The app failed to download the release archive. It looks like the `url` in `.bcr/core/source.template.json` is incorrect:
```
"https://github.com/{OWNER}/{REPO}/releases/download/{TAG}/${REPO}-${VERSION}.tar.gz"
```
(need to remove the `$`s)

I also need to do some more work around detecting errors and sending more helpful messages.
