### ISSUE TITLE
FR: allow multiple modules in one git repo

### ISSUE THREAD

**Issue by tetromino** [bazel-contrib/publish-to-bcr#46]
It was suggested that https://github.com/bazelbuild/bazel-skylib could adopt publish-to-bcr to simplify the maintainer's workflow.

The bazel-skylib git repo builds two separate Bazel modules: bazel_skylib and bazel_skylib_gazelle_plugin. The release process generates two separate release tarballs via rules_pkg (bazel-skylib-$VERSION.tar.gz and bazel-skylib-gazelle-plugin-$VERSION.tar.gz - see https://github.com/bazelbuild/bazel-skylib/releases/tag/1.4.0 for example) which then should be added to BCR in one commit (e.g. https://github.com/bazelbuild/bazel-central-registry/pull/403) because bazel_skylib_gazelle_plugin depends on bazel_skylib of the same version.

I am wondering if publish-to-bcr could accomodate this setup. It would require breaking the assumption that there is a 1-1 mapping between git repo and module.

One way to do it might be to allow subdirectories in the top-level .bcr template dir, with each subdir corresponding to a separate module.

**Comment by kormide** [comment]
I would like to be able to support skylib. I'll scope out some solutions and try to schedule some time this month to work on this.

**Comment by aignas** [comment]
Right now `rules_python` also has 2 modules.

**Comment by chrislovecnm** [comment]
Where is the entry point for this code? I am happy modify bcr to support more than one module.

**Comment by kormide** [comment]
> Where is the entry point for this code? I am happy modify bcr to support more than one module.

The entrypoint is the github webhook: https://github.com/bazel-contrib/publish-to-bcr/blob/main/src/application/cloudfunction/github-webhook-entrypoint.ts

**Comment by kormide** [comment]
Added support in https://github.com/bazel-contrib/publish-to-bcr/commit/11a22c4037e9609b988373b0ffa1f612e33382b2.
