### ISSUE TITLE
Is it possible to include patches in the publishing?

### ISSUE THREAD

**Issue by rickeylev** [bazel-contrib/publish-to-bcr#49]
I have a MODULE.bazel file that contains a couple dev-only lines, but those lines can't be marked as dev only yet (It's a `register_toolchains()` call, which doesn't allow dev_dependency=True until a newer Bazel version is out).

I can see BCR allows patches to be applied, as specified in the source.json config. And I see Publish to BCR has a source.json template file. However, I can't seem to figure out how to put a patch file in that template that Publish to BCR is happy with. I'm hoping I can have the patch automatically applied when publishing the BCR.

Is this possible and I just can't find the right syntax, or not possible?

**Comment by alexeagle** [comment]
I don't think that's possible currently, but note that as of https://github.com/bazel-contrib/publish-to-bcr/commit/6c8bb8f2281f4c31be7a508a248cf28ad5ccd530 this app does know how to produce a patch file and include in the PR it sends.
