### ISSUE TITLE
Allow setting Github team/more individuals to get tagged when publishing

### ISSUE THREAD

**Issue by luispadron** [bazel-contrib/publish-to-bcr#59]
A request regarding the information in: https://github.com/bazel-contrib/publish-to-bcr#a-note-on-release-automation.

As I understand it, we'd need to set a single GitHub user in `config.yml` in order to have tagging from the BCR PR to work correctly. That field also seems to configure the token used for the fork/PR, what we'd like:

 - Use the GitHub action bot to create the PR, don't mind if thats the associated committer (since GitHub teams can't be commit authors)
 - Allow setting list of other GitHub individuals/teams to tag on the BCR PR

**Comment by kormide** [comment]
> Use the GitHub action bot to create the PR, don't mind if thats the associated committer (since GitHub teams can't be commit authors)

The Publish to BCR app bot is always the creator of the pull request. I'm assuming that's in line with what you meant here?

> Allow setting list of other GitHub individuals/teams to tag on the BCR PR

I see. So you would like to just tag arbitrary people on the PR but continue to use your main org's fork of the BCR for the source of the pull requests?

**Comment by luispadron** [comment]
> The Publish to BCR app bot is always the creator of the pull request. I'm assuming that's in line with what you meant here?

Sorry, yep thats what I meant.

> I see. So you would like to just tag arbitrary people on the PR but continue to use your main org's fork of the BCR for the source of the pull requests?

Yeah exactly!

**Comment by kormide** [comment]
> 
> > I see. So you would like to just tag arbitrary people on the PR but continue to use your main org's fork of the BCR for the source of the pull requests?
> 
> Yeah exactly!

That should be fairly easy to do and I think it's a useful thing to add. I'll label this as an enhancement and pick it up when I get the chance.

**Comment by luispadron** [comment]
Perfect, thanks for the quick response!

**Comment by kormide** [comment]
In the meantime you can just continue to not set a fixedReleaser. The app should work—you just won't receive a notification for the pull requests or be notified of any errors.

**Comment by kormide** [comment]
Rather than adding more configuration for additional taggers, I'm thinking that I will always tag everyone listed as a maintainer in `metadata.json`.

**Comment by luispadron** [comment]
Makes sense to me!

**Comment by luispadron** [comment]
Hm though in our case, it's a Google group email and not an actual GitHub account. 

Would it email as well?

**Comment by kormide** [comment]
Ah, looking at your metadata file:
https://github.com/bazelbuild/bazel-central-registry/blob/main/modules/rules_ios/metadata.json#L3

There is another field for a maintainer that most other modules have, `github`, which points to the GitHub username of the maintainer. I'm not able to find docs on the schema, and I guess there isn't validation for that field since you don't have it for your module.

The idea was to send any error emails to the maintainer emails and tag their github handles in the PR comment. The latter won't work for your case since the group won't have a github user. You could add a `github` field and set an arbitrary user, but then only one person would be tagged and perhaps you wanted multiple. So maybe I do just need some additional configuration in `config.yml` to add additional users to be tagged..

**Comment by kormide** [comment]
@meteorcloudy Is there a schema for the list of maintainers in `metadata.json`? Are the fields arbitrary?

**Comment by meteorcloudy** [comment]
Yeah, it should look like:
```
     [{"name": "John Cater", "email": "jcater@google.com"},
       {"name": "Yun Peng", "github": "meteorcloudy"}]
```
as it's described here: https://docs.google.com/document/d/1moQfNcEIttsk6vYanNKIy3ZuK53hQUFq1b1r0rmsYVg/edit#bookmark=id.1i90c6c14zvx

**Comment by kormide** [comment]
@luispadron I deployed the changes in https://github.com/bazel-contrib/publish-to-bcr/pull/75, which will tag any maintainers with a `github` field in the BCR pull request. You could add any users you want to tag in addition to the group email that you already have.

I wanted to check if the above is sufficient for your use case, or if you think there's still a need for the other solution we discussed: a config.yml setting to just add additional github handles to tag in the pr.

**Comment by luispadron** [comment]
I think that resolves this issue and it make sense it's not possible to **tag** non GitHub users. 

I think in the future it would be nice to be able to receive email notifications for releases and such if folks want to manage this via a mailing list vs. maintaining this list.
