### ISSUE TITLE
Failed to publish entry for bazelbuild/rules_foreign_cc@0.10.0 to the Bazel Central Registry.

### ISSUE THREAD

**Issue by jsharpe** [bazel-contrib/publish-to-bcr#60]

**Comment by kormide** [comment]
It looks like the download of the release archive failed. Is the archive uploaded at the same time that the release is published? If it's uploaded after a delay, the app won't find it.

**Comment by kormide** [comment]
The original error was a `404` on downloading `https://github.com/bazelbuild/rules_foreign_cc/releases/download/0.10.1/rules_foreign_cc-0.10.1.tar.gz`, which appears to be a valid link now.

**Comment by jsharpe** [comment]
Yes I triggered the release pipeline by creating a GitHub release rather than pushing a tag as it's easy to do this via the web interface. I will push a tag instead next time!

**Comment by kormide** [comment]
There is a way to upload artifacts when doing a manual release, but it's easy to miss:

<img width="745" alt="Screen Shot 2023-10-26 at 9 17 13 PM" src="https://github.com/bazel-contrib/publish-to-bcr/assets/4948761/f3f559b9-fe3d-4682-86dc-d5b569469033">

**Comment by jsharpe** [comment]
Yes; but in this case we're using the rules-template github action to generate the artifacts. Github is missing a UI just to create a tag but not a release.. I guess it can be done via github.dev.
