### ISSUE TITLE
Surface failure logs in email

### ISSUE THREAD

**Issue by keith** [bazel-contrib/publish-to-bcr#94]
I got an email with an error like:

```
Failed to publish entry for keith/buildifier-prebuilt@6.4.0 to the Bazel Central Registry.

An unknown error occurred. Please report an issue here: https://github.com/bazel-contrib/publish-to-bcr/issues.
```

It would be nice if the rest of the info was accessible somewhere so I could debug more

**Comment by kormide** [comment]
Here's the error I'm seeing in the logs:
```
remote: Permission to keith/bazel-central-registry.git denied to publish-to-bcr[bot].
fatal: unable to access 'https://github.com/keith/bazel-central-registry.git/': The requested URL returned error: 403
```

I try not to post stack traces. This is a case where I should have a friendly error that gets sent in the email.

Re. the above issue, is the app installed to your fork of the BCR?

**Comment by keith** [comment]
Yep the app is installed:

<img width="711" alt="image" src="https://github.com/bazel-contrib/publish-to-bcr/assets/283886/2bbb0b04-73fa-4cba-9e51-5f44dad8f9d6">

Note it has worked before https://github.com/bazelbuild/bazel-central-registry/pull/868, I believe without any changes on my side

**Comment by kormide** [comment]
Ah, I think I've seen this before. I suspect it's just an intermittent GitHub error. I think the solution is to add some retry logic on the push. I'll leave this ticket open to track that, as well as better error messaging here.

**Comment by keith** [comment]
Thanks!

**Comment by brentleyjones** [comment]
I just got the same. Is there a way to force a resubmit?

**Comment by kormide** [comment]
> I just got the same. Is there a way to force a resubmit?

Captured the specific bug in https://github.com/bazel-contrib/publish-to-bcr/issues/97. There isn't currently a way to resubmit (tracked [here](https://github.com/bazel-contrib/publish-to-bcr/issues/9)), except to delete then re-create the GitHub release, or to just release a new patch version.

**Comment by arijit-sen** [comment]
I am facing a similar issue with private repos. The app works correctly with the public repos but when the repo is made private, whenever I release it throws the unknown error. Can someone confirm on the same?

**Comment by kormide** [comment]
> I am facing a similar issue with private repos. The app works correctly with the public repos but when the repo is made private, whenever I release it throws the unknown error. Can someone confirm on the same?

@arijit-sen the error that caused your entries to fail was related to [this issue](https://bazelbuild.slack.com/archives/C014RARENH0/p1707187780032139)–I sent you an email about it a while back. Beyond that issue, I can't whether it works with private repos because I haven't tested this case. Do you want to try again and we can see what happens?

**Comment by kormide** [comment]
Now that [retries](https://github.com/bazel-contrib/publish-to-bcr/commit/b3e277cd4288047cf60d739d561e27fda3b00e61) for pushing to the fork has landed, the original issues causing the "unknown error" emails in this thread have all been addressed. Closing.
