### ISSUE TITLE
Publishing to BCR failed for rules_haskell

### ISSUE THREAD

**Issue by avdv** [bazel-contrib/publish-to-bcr#98]
Hi.

After cutting a new release, I received an email from the Publish to BCR app:

> Failed to publish entry for tweag/rules_haskell@v0.18 to the Bazel Central Registry.
>
> An unknown error occurred. Please report an issue here: https://github.com/bazel-contrib/publish-to-bcr/issues.

What am I missing? Thanks!

**Comment by kormide** [comment]
Try removing `moduleRoots` from `config.yml` since the module is the root of your repository. Move the files un `.bcr/rules_haskell` directly into `.bcr`.

**Comment by avdv** [comment]
Thank you! I'll fix that and see if it works when pushing the next release.

**Comment by avdv** [comment]
Thank you @kormide, it worked like a charm :smile: !
